version: "3.8"

services:
  scores-image:
    build: .
    image: gilkin/scores-image
    container_name: blabla-container
    ports:
      - "8777:8777"
    volumes:
      - ./Scores.txt:/app/Scores.txt
    restart: unless-stopped