version: "3.8"

services:
  score_test:
    build: .            # This matches your built image name
    container_name: blabla-container
    ports:
      - "8777:5001"
    restart: unless-stopped  # Optional: ensures it restarts if it crashes